"""Initial schema with normalized tables

Revision ID: 0191273b4214
Revises:
Create Date: 2026-01-01 23:40:46.378763

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0191273b4214"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: PLR0915
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("actor_ip", sa.String(length=50), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_actor", "audit_logs", ["actor_type", "actor_id"], unique=False)
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_table(
        "flag_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("default_severity", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("auto_flag", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flag_types_category"), "flag_types", ["category"], unique=False)
    op.create_index(op.f("ix_flag_types_code"), "flag_types", ["code"], unique=True)
    op.create_table(
        "linkedin_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("linkedin_url", sa.String(length=500), nullable=False),
        sa.Column("linkedin_username", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("photo_url", sa.String(length=1000), nullable=True),
        sa.Column("profile_exists", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("data_source", sa.String(length=50), nullable=False),
        sa.Column(
            "last_fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkedin_profiles_linkedin_url"),
        "linkedin_profiles",
        ["linkedin_url"],
        unique=True,
    )
    op.create_index(
        op.f("ix_linkedin_profiles_linkedin_username"),
        "linkedin_profiles",
        ["linkedin_username"],
        unique=False,
    )
    op.create_table(
        "applicants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lever_id", sa.String(length=255), nullable=False),
        sa.Column("lever_opportunity_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("email", sa.String(length=500), nullable=False),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("linkedin_profile_id", sa.UUID(), nullable=True),
        sa.Column("resume_url", sa.String(length=1000), nullable=True),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("lever_stage", sa.String(length=255), nullable=True),
        sa.Column("lever_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_level", sa.String(length=50), nullable=True),
        sa.Column("validation_score", sa.Float(), nullable=True),
        sa.Column("flag_count", sa.Integer(), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["linkedin_profile_id"],
            ["linkedin_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_applicants_email"), "applicants", ["email"], unique=False)
    op.create_index(
        "ix_applicants_email_lower", "applicants", [sa.literal_column("lower(email)")], unique=False
    )
    op.create_index(op.f("ix_applicants_lever_id"), "applicants", ["lever_id"], unique=True)
    op.create_index(
        op.f("ix_applicants_lever_opportunity_id"),
        "applicants",
        ["lever_opportunity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_applicants_risk_level"), "applicants", ["risk_level"], unique=False)
    op.create_index(
        "ix_applicants_risk_validated",
        "applicants",
        ["risk_level", "last_validated_at"],
        unique=False,
    )
    op.create_table(
        "audit_log_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_log_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["audit_log_id"], ["audit_logs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_changes_audit_log_id"),
        "audit_log_changes",
        ["audit_log_id"],
        unique=False,
    )
    op.create_table(
        "linkedin_certifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("issuing_organization", sa.String(length=500), nullable=True),
        sa.Column("issue_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credential_id", sa.String(length=255), nullable=True),
        sa.Column("credential_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["linkedin_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_linkedin_cert_org", "linkedin_certifications", ["issuing_organization"], unique=False
    )
    op.create_index(
        op.f("ix_linkedin_certifications_profile_id"),
        "linkedin_certifications",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "linkedin_education",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("school", sa.String(length=500), nullable=False),
        sa.Column("school_linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("degree", sa.String(length=255), nullable=True),
        sa.Column("field_of_study", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("grade", sa.String(length=100), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["linkedin_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_linkedin_edu_school", "linkedin_education", ["school"], unique=False)
    op.create_index(
        op.f("ix_linkedin_education_profile_id"), "linkedin_education", ["profile_id"], unique=False
    )
    op.create_table(
        "linkedin_experiences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=500), nullable=False),
        sa.Column("company_linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["linkedin_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_linkedin_exp_company", "linkedin_experiences", ["company"], unique=False)
    op.create_index(
        op.f("ix_linkedin_experiences_profile_id"),
        "linkedin_experiences",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "linkedin_skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("endorsement_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["linkedin_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "name", name="uq_profile_skill"),
    )
    op.create_index("ix_linkedin_skill_name", "linkedin_skills", ["name"], unique=False)
    op.create_index(
        op.f("ix_linkedin_skills_profile_id"), "linkedin_skills", ["profile_id"], unique=False
    )
    op.create_table(
        "applicant_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("applicant_id", "source", name="uq_applicant_source"),
    )
    op.create_index(
        op.f("ix_applicant_sources_applicant_id"),
        "applicant_sources",
        ["applicant_id"],
        unique=False,
    )
    op.create_table(
        "validation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("triggered_by", sa.String(length=255), nullable=True),
        sa.Column("trigger_source", sa.String(length=255), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("risk_level", sa.String(length=50), nullable=True),
        sa.Column("rules_passed", sa.Integer(), nullable=False),
        sa.Column("rules_failed", sa.Integer(), nullable=False),
        sa.Column("rules_skipped", sa.Integer(), nullable=False),
        sa.Column("flags_raised", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_runs_applicant_id"), "validation_runs", ["applicant_id"], unique=False
    )
    op.create_index(op.f("ix_validation_runs_status"), "validation_runs", ["status"], unique=False)
    op.create_table(
        "flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("flag_type_id", sa.UUID(), nullable=False),
        sa.Column("validation_run_id", sa.UUID(), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flag_type_id"],
            ["flag_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["validation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "applicant_id", "flag_type_id", "is_active", name="uq_active_flag_per_applicant"
        ),
    )
    op.create_index("ix_flags_active_severity", "flags", ["is_active", "severity"], unique=False)
    op.create_index(op.f("ix_flags_applicant_id"), "flags", ["applicant_id"], unique=False)
    op.create_index(op.f("ix_flags_flag_type_id"), "flags", ["flag_type_id"], unique=False)
    op.create_index(op.f("ix_flags_severity"), "flags", ["severity"], unique=False)
    op.create_index(
        op.f("ix_flags_validation_run_id"), "flags", ["validation_run_id"], unique=False
    )
    op.create_table(
        "validation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("validation_run_id", sa.UUID(), nullable=False),
        sa.Column("rule_name", sa.String(length=255), nullable=False),
        sa.Column("rule_version", sa.String(length=50), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("was_skipped", sa.Boolean(), nullable=False),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["validation_run_id"],
            ["validation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_results_passed"), "validation_results", ["passed"], unique=False
    )
    op.create_index(
        op.f("ix_validation_results_rule_name"), "validation_results", ["rule_name"], unique=False
    )
    op.create_index(
        "ix_validation_results_run_passed",
        "validation_results",
        ["validation_run_id", "passed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_results_validation_run_id"),
        "validation_results",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "validation_run_config",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("validation_run_id", sa.UUID(), nullable=False),
        sa.Column("rule_name", sa.String(length=255), nullable=False),
        sa.Column("config_key", sa.String(length=255), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["validation_run_id"], ["validation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("validation_run_id", "rule_name", "config_key", name="uq_run_config"),
    )
    op.create_index(
        op.f("ix_validation_run_config_validation_run_id"),
        "validation_run_config",
        ["validation_run_id"],
        unique=False,
    )
    op.create_table(
        "flag_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flag_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["flag_id"], ["flags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flag_evidence_flag_id"), "flag_evidence", ["flag_id"], unique=False)
    op.create_table(
        "validation_result_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["result_id"], ["validation_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_result_evidence_result_id"),
        "validation_result_evidence",
        ["result_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: PLR0915
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_validation_result_evidence_result_id"), table_name="validation_result_evidence"
    )
    op.drop_table("validation_result_evidence")
    op.drop_index(op.f("ix_flag_evidence_flag_id"), table_name="flag_evidence")
    op.drop_table("flag_evidence")
    op.drop_index(
        op.f("ix_validation_run_config_validation_run_id"), table_name="validation_run_config"
    )
    op.drop_table("validation_run_config")
    op.drop_index(op.f("ix_validation_results_validation_run_id"), table_name="validation_results")
    op.drop_index("ix_validation_results_run_passed", table_name="validation_results")
    op.drop_index(op.f("ix_validation_results_rule_name"), table_name="validation_results")
    op.drop_index(op.f("ix_validation_results_passed"), table_name="validation_results")
    op.drop_table("validation_results")
    op.drop_index(op.f("ix_flags_validation_run_id"), table_name="flags")
    op.drop_index(op.f("ix_flags_severity"), table_name="flags")
    op.drop_index(op.f("ix_flags_flag_type_id"), table_name="flags")
    op.drop_index(op.f("ix_flags_applicant_id"), table_name="flags")
    op.drop_index("ix_flags_active_severity", table_name="flags")
    op.drop_table("flags")
    op.drop_index(op.f("ix_validation_runs_status"), table_name="validation_runs")
    op.drop_index(op.f("ix_validation_runs_applicant_id"), table_name="validation_runs")
    op.drop_table("validation_runs")
    op.drop_index(op.f("ix_applicant_sources_applicant_id"), table_name="applicant_sources")
    op.drop_table("applicant_sources")
    op.drop_index(op.f("ix_linkedin_skills_profile_id"), table_name="linkedin_skills")
    op.drop_index("ix_linkedin_skill_name", table_name="linkedin_skills")
    op.drop_table("linkedin_skills")
    op.drop_index(op.f("ix_linkedin_experiences_profile_id"), table_name="linkedin_experiences")
    op.drop_index("ix_linkedin_exp_company", table_name="linkedin_experiences")
    op.drop_table("linkedin_experiences")
    op.drop_index(op.f("ix_linkedin_education_profile_id"), table_name="linkedin_education")
    op.drop_index("ix_linkedin_edu_school", table_name="linkedin_education")
    op.drop_table("linkedin_education")
    op.drop_index(
        op.f("ix_linkedin_certifications_profile_id"), table_name="linkedin_certifications"
    )
    op.drop_index("ix_linkedin_cert_org", table_name="linkedin_certifications")
    op.drop_table("linkedin_certifications")
    op.drop_index(op.f("ix_audit_log_changes_audit_log_id"), table_name="audit_log_changes")
    op.drop_table("audit_log_changes")
    op.drop_index("ix_applicants_risk_validated", table_name="applicants")
    op.drop_index(op.f("ix_applicants_risk_level"), table_name="applicants")
    op.drop_index(op.f("ix_applicants_lever_opportunity_id"), table_name="applicants")
    op.drop_index(op.f("ix_applicants_lever_id"), table_name="applicants")
    op.drop_index("ix_applicants_email_lower", table_name="applicants")
    op.drop_index(op.f("ix_applicants_email"), table_name="applicants")
    op.drop_table("applicants")
    op.drop_index(op.f("ix_linkedin_profiles_linkedin_username"), table_name="linkedin_profiles")
    op.drop_index(op.f("ix_linkedin_profiles_linkedin_url"), table_name="linkedin_profiles")
    op.drop_table("linkedin_profiles")
    op.drop_index(op.f("ix_flag_types_code"), table_name="flag_types")
    op.drop_index(op.f("ix_flag_types_category"), table_name="flag_types")
    op.drop_table("flag_types")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
