"""Add review status fields to applicants

Revision ID: 07f1931b97ff
Revises: 0191273b4214
Create Date: 2026-01-02 00:06:14.233961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07f1931b97ff"
down_revision: str | Sequence[str] | None = "0191273b4214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applicants", sa.Column("is_reviewed", sa.Boolean(), nullable=False))
    op.add_column("applicants", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("applicants", sa.Column("reviewed_by", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applicants", "reviewed_by")
    op.drop_column("applicants", "reviewed_at")
    op.drop_column("applicants", "is_reviewed")
    # ### end Alembic commands ###
