"""add lever owner fields

Revision ID: 46f4a85f5c34
Revises: 07f1931b97ff
Create Date: 2026-01-07 09:40:34.701373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46f4a85f5c34"
down_revision: str | Sequence[str] | None = "07f1931b97ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applicants", sa.Column("lever_owner_id", sa.String(length=255), nullable=True))
    op.add_column("applicants", sa.Column("lever_owner_name", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applicants", "lever_owner_name")
    op.drop_column("applicants", "lever_owner_id")
    # ### end Alembic commands ###
