"""Add is_manually_added to applicants

Revision ID: ded2f381692a
Revises: b9f8c4d5e6a2
Create Date: 2026-01-08 09:15:49.117401

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ded2f381692a"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "b9f8c4d5e6a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with server_default to handle existing rows, then optionally remove the default
    op.add_column(
        "applicants",
        sa.Column("is_manually_added", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applicants", "is_manually_added")
    # ### end Alembic commands ###
