"""Database module for applicant validator."""

from applicant_validator.database.base import Base, get_db_session, get_session, init_db
from applicant_validator.database.models import (
    Applicant,
    ApplicantPosting,
    ApplicantSource,
    AuditAction,
    AuditLog,
    AuditLogChange,
    Flag,
    FlagCategory,
    FlagEvidence,
    FlagSeverity,
    FlagType,
    LeverPosting,
    LinkedInCertification,
    LinkedInEducation,
    LinkedInExperience,
    LinkedInProfile,
    LinkedInSkill,
    RiskLevel,
    SystemConfig,
    User,
    UserRole,
    UserSession,
    ValidationResult,
    ValidationResultEvidence,
    ValidationRun,
    ValidationRunConfig,
    ValidationStatus,
)

__all__ = [
    # Core models
    "Applicant",
    "ApplicantPosting",
    "ApplicantSource",
    # Enums
    "AuditAction",
    "AuditLog",
    "AuditLogChange",
    # Base and utilities
    "Base",
    "Flag",
    "FlagCategory",
    "FlagEvidence",
    "FlagSeverity",
    "FlagType",
    "LeverPosting",
    "LinkedInCertification",
    "LinkedInEducation",
    "LinkedInExperience",
    "LinkedInProfile",
    "LinkedInSkill",
    "RiskLevel",
    "SystemConfig",
    # Auth models
    "User",
    "UserRole",
    "UserSession",
    "ValidationResult",
    "ValidationResultEvidence",
    "ValidationRun",
    "ValidationRunConfig",
    "ValidationStatus",
    "get_db_session",
    "get_session",
    "init_db",
]
